const estacionamentos = [
  {
    address: "Rua Anita Garibaldi, N°519, Sé, 01018-020",
    preco: [50.0, 70.0, 10.0],
    imgPath: "graphics/Estacionamento1.png",
    vagasMax: 100,
    vagasOcupadas: 0,
    descricao: "Um dos nossos melhores estacionamentos em São Paulo, com a guarda automatica do automovel, sem a necessidade de um condutor. Estacionamento subterraneo, bem protegido e fora do perigo da superficie, tambem evitando chuvas e a sujeira.",
    servicos: ["Wifi", "Área Coberta", "Estacionamento subterraneo"],
  },
  {
    address: "Av. Cruzeiro do Sul, N°3345, Santana, 02030-200",
    preco: [10.0, 20.0, 5.0],
    imgPath: "graphics/Estacionamento2.png",
    vagasMax: 100,
    vagasOcupadas: 0,
    descricao: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Est officia perspiciatis nulla maiores expedita optio aliquam, sapiente veniam nisi, atque ab numquam eius temporibus ipsum ipsa libero laborum quas dolorum.",
    servicos: ["Wifi"],
  },
  {
    address: "Av. Jacu Pêssego, N°1948, Itaquera, 08260-005",
    preco: [10.0, 20.0, 5.0],
    imgPath: "graphics/Estacionamento3.png",
    vagasMax: 100,
    vagasOcupadas: 0,
    descricao: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Est officia perspiciatis nulla maiores expedita optio aliquam, sapiente veniam nisi, atque ab numquam eius temporibus ipsum ipsa libero laborum quas dolorum.",
    servicos: ["Wifi"],
  },
  {
    address: "Rua Clélia, N°281, Lapa, 02675-031",
    preco: [10.0, 20.0, 5.0],
    imgPath: "graphics/Estacionamento4.png",
    vagasMax: 100,
    vagasOcupadas: 0,
    descricao: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Est officia perspiciatis nulla maiores expedita optio aliquam, sapiente veniam nisi, atque ab numquam eius temporibus ipsum ipsa libero laborum quas dolorum.",
    servicos: ["Wifi", "Área Coberta"],
  },
  {
    address: "Rua Clélia, N°281, Lapa, 02675-031",
    preco: [10.0, 20.0, 5.0],
    imgPath: "graphics/Estacionamento4.png",
    vagasMax: 100,
    vagasOcupadas: 0,
    descricao: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Est officia perspiciatis nulla maiores expedita optio aliquam, sapiente veniam nisi, atque ab numquam eius temporibus ipsum ipsa libero laborum quas dolorum.",
    servicos: ["Wifi", "Área Coberta"],
  },
]